from datetime import datetime, timedelta

sample_alerts = [
    {
        "id": "1",
        "timestamp": datetime.now() - timedelta(minutes=5),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "negative",
        "text": "Terrible customer service experience. Waited 2 hours for support.",
        "author": "@frustrated_user",
        "urgency": "high",
        # "recommendedResponse": "Immediate personal outreach with senior support manager.",
        "metrics": {"engagement": 45, "reach": 1200}
    },
    {
        "id": "2",
        "timestamp": datetime.now() - timedelta(minutes=15),
        "source": "Google Reviews",
        "platform": "reviews",
        "sentiment": "negative",
        "text": "Product quality has declined significantly. Very disappointed.",
        "author": "Sarah M.",
        "urgency": "medium",
        # "recommendedResponse": "Quality team investigation recommended.",
        "metrics": {"rating": 2, "helpful": 8}
    },
    {
        "id": "3",
        "timestamp": datetime.now() - timedelta(minutes=30),
        "source": "Reddit",
        "platform": "forum",
        "sentiment": "negative",
        "text": "Anyone else having issues with their recent update? App crashes constantly.",
        "author": "techuser2024",
        "urgency": "medium",
        # "recommendedResponse": "Technical team to provide update timeline.",
        "metrics": {"upvotes": 23, "comments": 12}
    },
    {
        "id": "4",
        "timestamp": datetime.now() - timedelta(minutes=45),
        "source": "App Store",
        "platform": "reviews",
        "sentiment": "very-negative",
        "text": "App is unusable after the last update. Please fix ASAP!",
        "author": "iOSUser99",
        "urgency": "high",
        # "recommendedResponse": "Technical team to provide update patch.",
        "metrics": {"rating": 1, "helpful": 15}
    },
    {
        "id": "5",
        "timestamp": datetime.now() - timedelta(minutes=60),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "negative",
        "text": "Received wrong item in my order. Very frustrating experience.",
        "author": "@unhappy_customer",
        "urgency": "medium",
        # "recommendedResponse": "Customer service to arrange replacement immediately.",
        "metrics": {"engagement": 30, "reach": 800}
    },
      {
        "id": "6",
        "timestamp": datetime.now() - timedelta(minutes=10),
        "source": "App Store",
        "platform": "reviews",
        "sentiment": "very-negative",
        "text": "Latest update broke everything. Can't log in anymore.",
        "author": "AppUser_iOS",
        "urgency": "high",
        # "recommendedResponse": "Escalate to dev team and provide emergency patch timeline.",
        "metrics": {"rating": 1, "helpful": 15}
    },
    {
        "id": "7",
        "timestamp": datetime.now() - timedelta(minutes=20),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "negative",
        "text": "Customer support was unhelpful, no resolution given.",
        "author": "@angrycustomer",
        "urgency": "medium",
        # "recommendedResponse": "Reach out personally and provide compensation.",
        "metrics": {"engagement": 30, "reach": 800}
    },
    {
        "id": "8",
        "timestamp": datetime.now() - timedelta(minutes=25),
        "source": "Reddit",
        "platform": "forum",
        "sentiment": "neutral",
        "text": "The product is okay, but could use improvements in design.",
        "author": "techlover92",
        "urgency": "low",
        # "recommendedResponse": "Collect feedback for next update release.",
        "metrics": {"upvotes": 12, "comments": 3}
    },
    {
        "id": "9",
        "timestamp": datetime.now() - timedelta(minutes=35),
        "source": "Google Reviews",
        "platform": "reviews",
        "sentiment": "positive",
        "text": "Fast delivery and excellent packaging. Very satisfied.",
        "author": "John D.",
        "urgency": "low",
        # "recommendedResponse": "Thank the customer and encourage review sharing.",
        "metrics": {"rating": 5, "helpful": 10}
    },
    {
        "id": "10",
        "timestamp": datetime.now() - timedelta(minutes=40),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "very-negative",
        "text": "Received a defective product. Completely unacceptable.",
        "author": "@disappointed_user",
        "urgency": "high",
        # "recommendedResponse": "Immediate replacement and apology required.",
        "metrics": {"engagement": 50, "reach": 1400}
    },
    {
        "id": "11",
        "timestamp": datetime.now() - timedelta(minutes=50),
        "source": "Facebook",
        "platform": "forum",
        "sentiment": "negative",
        "text": "Support team takes too long to respond. Frustrating experience.",
        "author": "Emily R.",
        "urgency": "medium",
        # "recommendedResponse": "Follow up promptly and offer assistance.",
        "metrics": {"comments": 5, "shares": 2}
    },
    {
        "id": "12",
        "timestamp": datetime.now() - timedelta(minutes=55),
        "source": "Reddit",
        "platform": "forum",
        "sentiment": "neutral",
        "text": "Product is functional but the setup instructions are unclear.",
        "author": "gadgetfan123",
        "urgency": "low",
        # "recommendedResponse": "Provide a clear setup guide and FAQs.",
        "metrics": {"upvotes": 8, "comments": 2}
    },
    {
        "id": "13",
        "timestamp": datetime.now() - timedelta(minutes=65),
        "source": "Google Reviews",
        "platform": "reviews",
        "sentiment": "positive",
        "text": "Great customer service! My issue was resolved quickly.",
        "author": "Alice P.",
        "urgency": "low",
        # "recommendedResponse": "Thank the customer and encourage repeat business.",
        "metrics": {"rating": 5, "helpful": 7}
    },
    {
        "id": "14",
        "timestamp": datetime.now() - timedelta(minutes=70),
        "source": "App Store",
        "platform": "reviews",
        "sentiment": "negative",
        "text": "App crashes frequently on my device. Needs fixing.",
        "author": "AndroidUser77",
        "urgency": "medium",
        # "recommendedResponse": "Investigate crash logs and provide patch update.",
        "metrics": {"rating": 2, "helpful": 9}
    },
    {
        "id": "15",
        "timestamp": datetime.now() - timedelta(minutes=80),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "positive",
        "text": "Really happy with the quick support response today!",
        "author": "@happyuser",
        "urgency": "low",
        # "recommendedResponse": "Acknowledge and thank the customer.",
        "metrics": {"engagement": 20, "reach": 500}
    },
    {
        "id": "16",
        "timestamp": datetime.now() - timedelta(minutes=90),
        "source": "Facebook",
        "platform": "forum",
        "sentiment": "very-negative",
        "text": "Absolutely terrible service. Waiting for support for 3 days!",
        "author": "MikeT",
        "urgency": "high",
        # "recommendedResponse": "Immediate outreach and apology. Escalate to senior team.",
        "metrics": {"comments": 12, "shares": 4}
    },
    {
        "id": "17",
        "timestamp": datetime.now() - timedelta(minutes=95),
        "source": "Google Reviews",
        "platform": "reviews",
        "sentiment": "negative",
        "text": "Product arrived damaged. Very disappointed.",
        "author": "Laura S.",
        "urgency": "medium",
        # "recommendedResponse": "Send replacement immediately and apologize.",
        "metrics": {"rating": 1, "helpful": 5}
    },
    {
        "id": "18",
        "timestamp": datetime.now() - timedelta(minutes=100),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "neutral",
        "text": "The product is decent, but shipping took too long.",
        "author": "@averageuser",
        "urgency": "low",
        # "recommendedResponse": "Thank customer and provide shipping improvement update.",
        "metrics": {"engagement": 10, "reach": 300}
    },
    {
        "id": "19",
        "timestamp": datetime.now() - timedelta(minutes=110),
        "source": "Reddit",
        "platform": "forum",
        "sentiment": "positive",
        "text": "Love the new update, very user-friendly!",
        "author": "redditor123",
        "urgency": "low",
        # "recommendedResponse": "Thank customer for feedback.",
        "metrics": {"upvotes": 25, "comments": 4}
    },
    {
        "id": "20",
        "timestamp": datetime.now() - timedelta(minutes=115),
        "source": "App Store",
        "platform": "reviews",
        "sentiment": "very-negative",
        "text": "App keeps crashing after update. Useless now.",
        "author": "iOSfan88",
        "urgency": "high",
        # "recommendedResponse": "Escalate to dev team, provide urgent fix.",
        "metrics": {"rating": 1, "helpful": 20}
    },
    {
        "id": "21",
        "timestamp": datetime.now() - timedelta(minutes=120),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "negative",
        "text": "Customer service was rude and unhelpful.",
        "author": "@frustrated_user",
        "urgency": "medium",
        # "recommendedResponse": "Reach out with apology and compensation offer.",
        "metrics": {"engagement": 40, "reach": 900}
    },
    {
        "id": "22",
        "timestamp": datetime.now() - timedelta(minutes=125),
        "source": "Google Reviews",
        "platform": "reviews",
        "sentiment": "neutral",
        "text": "Delivery was on time but packaging was poor.",
        "author": "Ben K.",
        "urgency": "low",
        # "recommendedResponse": "Thank customer and improve packaging.",
        "metrics": {"rating": 3, "helpful": 2}
    },
    {
        "id": "23",
        "timestamp": datetime.now() - timedelta(minutes=130),
        "source": "Reddit",
        "platform": "forum",
        "sentiment": "positive",
        "text": "Amazing support experience, resolved quickly!",
        "author": "techfan89",
        "urgency": "low",
        # "recommendedResponse": "Thank customer and encourage positive review.",
        "metrics": {"upvotes": 30, "comments": 6}
    },
    {
        "id": "24",
        "timestamp": datetime.now() - timedelta(minutes=135),
        "source": "App Store",
        "platform": "reviews",
        "sentiment": "negative",
        "text": "App is buggy and slow after latest update.",
        "author": "AppUserX",
        "urgency": "medium",
        # "recommendedResponse": "Technical team to fix bugs and notify users.",
        "metrics": {"rating": 2, "helpful": 8}
    },
    {
        "id": "25",
        "timestamp": datetime.now() - timedelta(minutes=140),
        "source": "Facebook",
        "platform": "forum",
        "sentiment": "positive",
        "text": "Product quality exceeded expectations. Very happy!",
        "author": "Samantha R.",
        "urgency": "low",
        # "recommendedResponse": "Thank the customer and request testimonial.",
        "metrics": {"comments": 3, "shares": 1}
    },
     {
        "id": "26",
        "timestamp": datetime.now() - timedelta(minutes=145),
        "source": "Twitter",
        "platform": "twitter",
        "sentiment": "very-negative",
        "text": "Worst experience ever! Support never responded.",
        "author": "@angrycustomer",
        "urgency": "high",
        # "recommendedResponse": "Immediate personal follow-up and apology.",
        "metrics": {"engagement": 55, "reach": 1200}
    },
    {
        "id": "27",
        "timestamp": datetime.now() - timedelta(minutes=150),
        "source": "Google Reviews",
        "platform": "reviews",
        "sentiment": "negative",
        "text": "Item was missing parts, very disappointed.",
        "author": "John D.",
        "urgency": "medium",
        # "recommendedResponse": "Offer replacement or refund promptly.",
        "metrics": {"rating": 1, "helpful": 6}
    },
    {
        "id": "28",
        "timestamp": datetime.now() - timedelta(minutes=155),
        "source": "Reddit",
        "platform": "forum",
        "sentiment": "neutral",
        "text": "Product works okay, shipping could be faster.",
        "author": "tech_guy_2025",
        "urgency": "low",
        # "recommendedResponse": "Thank customer and provide shipping updates.",
        "metrics": {"upvotes": 12, "comments": 3}
    },
    {
        "id": "29",
        "timestamp": datetime.now() - timedelta(minutes=160),
        "source": "App Store",
        "platform": "reviews",
        "sentiment": "positive",
        "text": "Great app experience, very intuitive interface!",
        "author": "iOSlover77",
        "urgency": "low",
        # "recommendedResponse": "Thank customer and encourage sharing experience.",
        "metrics": {"rating": 5, "helpful": 10}
    },
    {
        "id": "30",
        "timestamp": datetime.now() - timedelta(minutes=165),
        "source": "Facebook",
        "platform": "forum",
        "sentiment": "negative",
        "text": "Received wrong product, very frustrating.",
        "author": "Emma W.",
        "urgency": "medium",
        # "recommendedResponse": "Arrange replacement and apologize for inconvenience.",
        "metrics": {"comments": 8, "shares": 2}
    }
]
